version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    volumes:
      - ../:/mastodon
    working_dir: /mastodon
    environment:
      LOCAL_DOMAIN: mastodon.local
      RAILS_ENV: development
      NODE_ENV: development
      BIND: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_PORT: '5432'
      # Uncomment to enable elasticsearch
      # ES_ENABLED: 'true'
      # ES_HOST: es
      # ES_PORT: '9200'
      LIBRE_TRANSLATE_ENDPOINT: http://libretranslate:5000
    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    entrypoint: /mastodon/dev/entrypoint.sh
    ports:
      # mastodon app
      - '127.0.0.1:3000:3000'
      # webpack app
      - '127.0.0.1:3035:3035'
      # streaming app
      - '127.0.0.1:4000:4000'
    networks:
      - external_network
      - internal_network

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ../postgres14:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - internal_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - internal_network

  # Uncomment to enable ES
  # This was copied from `.devcontainer` setup and
  # is untested...
  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  #   restart: unless-stopped
  #   environment:
  #     ES_JAVA_OPTS: -Xms512m -Xmx512m
  #     cluster.name: es-mastodon
  #     discovery.type: single-node
  #     bootstrap.memory_lock: 'true'
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  #   networks:
  #     - internal_network
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1

  libretranslate:
    image: libretranslate/libretranslate:v1.5.5
    restart: unless-stopped
    volumes:
      - lt-data:/home/libretranslate/.local
    networks:
      - external_network
      - internal_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - 'app'
    links:
      - 'app:app'
    volumes:
      - ../public:/mastodon/public
      - ./mastodon.local.conf:/etc/nginx/conf.d/mastodon.local.conf
    networks:
      - external_network
      - internal_network

volumes:
  redis-data:
  es-data:
  lt-data:

networks:
  external_network:
  internal_network:
    internal: true
